### ISSUE TITLE
Charts breaks on too high values

### ISSUE THREAD

**Issue by maxux** [markbattistella/docsify-charty#19]
Hello,

Using very large values, charts doesn't draw correctly. Numbers are well computed on the legend, but chart breaks.
See here, using values divided by 1000 to get them lower, and then real values:

![image](https://user-images.githubusercontent.com/4141584/115863405-af86c880-a435-11eb-986b-c3a5333d732d.png)

![image](https://user-images.githubusercontent.com/4141584/115863235-7b130c80-a435-11eb-99b7-a6c035023e83.png)

As you can see, percentage are well computed on the legend, but render is broken :/

**Comment by markbattistella** [comment]
interesting! i think this will be solved in v2.0.0 but there's no fixed date yet for it - hopefully soon. i'll have a look at this as it might be a little math issue i've missed out with

**Comment by maxux** [comment]
I checked quickly the code, it could be svg limitation, I don’t recall but
maybe you use values to compute size and not percentage, and numbers
doesn’t fit in 32 bits, maybe there are some limitation there.

Using percentage to draw would probably fix that, but didn’t had time to
check :/

**Comment by markbattistella** [comment]
@maxux Okay, I figured out the issue - bing the numbers are in fact too large. Which is a pain, as you demonstrated not everything can fit in the `<500000` block.

Now, v2.0.0 will fix this but isn't ready now (hoping by end of June!)

Temporary fix:

It's not a donut/doughnut but can be a normal pie chart. It involves a bit of manual math, and you do lose the value in the legend,

You can sum the total values, then calculate the percentage then place that into a section/sectional chart.

**Comment by markbattistella** [comment]
@maxux I've updated the charty to v2.0.0 it should fix your problem, but does have a bit more of functionality. It is a major change so please read the docs :)
