### ISSUE TITLE
Unable to get it to work

### ISSUE THREAD

**Issue by Azurelol** [markbattistella/docsify-charty#24]
Hello.

I have been unable to get it to work. I updated the index.html file, trying both with unpk.com and jsDelivr.com.
I tried several of the samples but none of them rendered.

Is the configuration block required? I tried putting in what I thought would be valid values for the theme and mode but it didn't make it work. I saw i it's empty on your index.html so I also tried it without.

**Comment by markbattistella** [comment]
@Azurelol did you have a demo repo or some of your code samples used - if I can see it I'll be able to see what's causing issues 😄

**Comment by markbattistella** [comment]
@Azurelol I think under your `index.html` file the chart config section:
 
```
charty: {
  "theme": String,
  "mode":  String
},
```

The theme and mode accept string values.

So you could have:

```
charty: {
  "theme": "#EE5599",
  "mode":  "dark"
},
```

I've added into the demo site: https://markbattistella.github.io/docsify-charty-docs/#/?id=global-settings

**Comment by markbattistella** [comment]
I assume this has resolved the issue..

**Comment by Azurelol** [comment]
Sorry, but it did not. 

When I first tried the index.html, I did have filled in the values for the charty configuration originally. but at the time I copied it again with the placeholders.

**Comment by markbattistella** [comment]
Are you able to share the repo with me? Or are you able to add: the `debug` to your config:

```js
charty: {
    "debug": true
}
```

Then in the console log of your browser it might have a better indication of what is happening

**Comment by markbattistella** [comment]
@Azurelol any luck?

**Comment by Azurelol** [comment]
Sorry for the delay in getting back to you; I only noticed the notification from the issue being re-opened. Thank you for that.

I will try the debug property, then if that doesn't help I will create a repository that has the configuration I use (the original repo is private, used for work) . I will let you know of my findings.

**Comment by markbattistella** [comment]
absolutely! i'd love to see if there are issues so i can fix them for you :)

**Comment by Azurelol** [comment]
Hello. I have created a sample repo with the same setup as the original. 
The [repository](https://github.com/Azurelol/docsify-charty-test) and the [Github page](https://azurelol.github.io/docsify-charty-test/#/).

**Comment by markbattistella** [comment]
@Azurelol - okay I see the problem!

I made a PR on your repo, but also forked it so you can see it working exactly as you made it:

https://github.com/markbattistella/docsify-charty-test
https://markbattistella.github.io/docsify-charty-test/

What you were missing on your info was:

- the code block (three backticks)
- adding the `charty` language

**Comment by Azurelol** [comment]
Thank you! I can confirm it works.

I see you also are updating the main README to inform users about having it nested within a code block.
