### ISSUE TITLE
Radar chart example not working

### ISSUE THREAD

**Issue by Azurelol** [markbattistella/docsify-charty#25]
Hello!

What would be the correct way to use the radar charts? The example for them in the docs doesn't work.

https://markbattistella.github.io/docsify-charty-docs/#/?id=docsify-charty

**Comment by Azurelol** [comment]
![image](https://user-images.githubusercontent.com/10147802/134041266-adf5d92f-503f-48e2-8c2e-765eefe55083.png)

**Comment by markbattistella** [comment]
Sorry, I just tested it in other browsers and didn't realise. Seems to be fixed now, but if you can test it.

Commit number: 86af5363c13a9c4adc44e72475b62b8335e0c690
