### ISSUE TITLE
Firefox rendering issues

### ISSUE THREAD

**Issue by Azurelol** [markbattistella/docsify-charty#26]
Hello; I ran another test this morning as a follow-up to #25; the rendering issue still persists on Firefox for several of the charts. So far I tested it with Donut and Radar.

![image](https://user-images.githubusercontent.com/10147802/134133217-31d6bd6b-4527-4ade-b362-1bc63ac227be.png)

(I also noticed the Bar chart doesn't work when there's a key with only one value, but that's a separate issue)

**Comment by markbattistella** [comment]
Hi @Azurelol thanks for all these - makes the plugin better.

I'm trying to replicate the issues - donut looking like a pie, and the radar labels.

I'm on both macOS - Safari, Chrome, Firefox, and Opera - they all look as they should.
On Windows 10 - Chrome, Firefox, Edge - they all look like they should.

What OS and browser are you using?

**Comment by markbattistella** [comment]
I made a test repo here: https://github.com/markbattistella/docsify-charty-test and demo site: https://markbattistella.github.io/docsify-charty-test/

**Comment by Azurelol** [comment]
Thank you for getting back to me so promptly!

I saw the repo, and it rendered correctly for me (on Firefox, Windows 10).

I was testing the different charts on the test repo I made previously:
https://azurelol.github.io/docsify-charty-test/#/

**Comment by markbattistella** [comment]
okay - thanks for those links. I'll have to do some more tests to make sure but it seems that 2.0.2 is working for Firefox on Windows? 

I've noticed some other bugs which i'll look into. 

Are you still seeing issues on the radar?

If you have other issues i'd appreciate if you could log them separately so I can help keep track of them for you and close them off incrementally 😃
